# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TrackingInfo.ui',
# licensing of 'TrackingInfo.ui' applies.
#
# Created: Wed May 29 14:44:54 2019
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(800, 600))
        Form.setMaximumSize(QtCore.QSize(800, 600))
        Form.setBaseSize(QtCore.QSize(800, 600))
        self.bg = QtWidgets.QLabel(Form)
        self.bg.setGeometry(QtCore.QRect(0, 0, 801, 601))
        self.bg.setStyleSheet("QLabel{background: lightcyan;}")
        self.bg.setText("")
        self.bg.setObjectName("bg")
        self.Tracking_Number = QtWidgets.QLabel(Form)
        self.Tracking_Number.setGeometry(QtCore.QRect(170, 30, 481, 71))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(20)
        font.setWeight(75)
        font.setItalic(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(True)
        self.Tracking_Number.setFont(font)
        self.Tracking_Number.setStyleSheet("QLabel{color:slategrey;}\n"
"")
        self.Tracking_Number.setObjectName("Tracking_Number")
        self.Info = QtWidgets.QLabel(Form)
        self.Info.setGeometry(QtCore.QRect(50, 120, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(16)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.Info.setFont(font)
        self.Info.setObjectName("Info")
        self.confirm = QtWidgets.QCommandLinkButton(Form)
        self.confirm.setGeometry(QtCore.QRect(630, 530, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.confirm.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("shipping.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.confirm.setIcon(icon)
        self.confirm.setObjectName("confirm")
        self.rname = QtWidgets.QLabel(Form)
        self.rname.setGeometry(QtCore.QRect(100, 360, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        self.rname.setFont(font)
        self.rname.setObjectName("rname")
        self.sname = QtWidgets.QLabel(Form)
        self.sname.setGeometry(QtCore.QRect(100, 190, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        self.sname.setFont(font)
        self.sname.setObjectName("sname")
        self.senderAdd = QtWidgets.QLabel(Form)
        self.senderAdd.setGeometry(QtCore.QRect(400, 190, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        self.senderAdd.setFont(font)
        self.senderAdd.setObjectName("senderAdd")
        self.raddr = QtWidgets.QLabel(Form)
        self.raddr.setGeometry(QtCore.QRect(420, 350, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        self.raddr.setFont(font)
        self.raddr.setObjectName("raddr")
        self.shipmenttype = QtWidgets.QLabel(Form)
        self.shipmenttype.setGeometry(QtCore.QRect(270, 480, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        self.shipmenttype.setFont(font)
        self.shipmenttype.setObjectName("shipmenttype")
        self.showtrackingnumber = QtWidgets.QLabel(Form)
        self.showtrackingnumber.setGeometry(QtCore.QRect(470, 30, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        font.setWeight(75)
        font.setItalic(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(True)
        self.showtrackingnumber.setFont(font)
        self.showtrackingnumber.setStyleSheet("QLabel{color:lightgrey;}\n"
"")
        self.showtrackingnumber.setObjectName("showtrackingnumber")
        self.showsname = QtWidgets.QLabel(Form)
        self.showsname.setGeometry(QtCore.QRect(240, 190, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.showsname.setFont(font)
        self.showsname.setStyleSheet("QLabel{color:lightgrey;}\n"
"")
        self.showsname.setObjectName("showsname")
        self.showsAdd = QtWidgets.QLabel(Form)
        self.showsAdd.setGeometry(QtCore.QRect(550, 170, 211, 81))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.showsAdd.setFont(font)
        self.showsAdd.setStyleSheet("QLabel{color:lightgrey;}\n"
"")
        self.showsAdd.setObjectName("showsAdd")
        self.showrname = QtWidgets.QLabel(Form)
        self.showrname.setGeometry(QtCore.QRect(240, 360, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.showrname.setFont(font)
        self.showrname.setStyleSheet("QLabel{color:lightgrey;}\n"
"")
        self.showrname.setObjectName("showrname")
        self.showradd = QtWidgets.QLabel(Form)
        self.showradd.setGeometry(QtCore.QRect(580, 330, 211, 81))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.showradd.setFont(font)
        self.showradd.setStyleSheet("QLabel{color:lightgrey;}\n"
"")
        self.showradd.setObjectName("showradd")
        self.sendercon = QtWidgets.QLabel(Form)
        self.sendercon.setGeometry(QtCore.QRect(100, 250, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        self.sendercon.setFont(font)
        self.sendercon.setObjectName("sendercon")
        self.showsendercon = QtWidgets.QLabel(Form)
        self.showsendercon.setGeometry(QtCore.QRect(320, 260, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.showsendercon.setFont(font)
        self.showsendercon.setStyleSheet("QLabel{color:lightgrey;}\n"
"")
        self.showsendercon.setObjectName("showsendercon")
        self.showrcon = QtWidgets.QLabel(Form)
        self.showrcon.setGeometry(QtCore.QRect(330, 420, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.showrcon.setFont(font)
        self.showrcon.setStyleSheet("QLabel{color:lightgrey;}\n"
"")
        self.showrcon.setObjectName("showrcon")
        self.rcon = QtWidgets.QLabel(Form)
        self.rcon.setGeometry(QtCore.QRect(100, 410, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        self.rcon.setFont(font)
        self.rcon.setObjectName("rcon")
        self.pic = QtWidgets.QLabel(Form)
        self.pic.setGeometry(QtCore.QRect(70, 20, 81, 81))
        self.pic.setText("")
        self.pic.setPixmap(QtGui.QPixmap("open-parcel copy 2.png"))
        self.pic.setObjectName("pic")
        self.showshipmenttype_2 = QtWidgets.QLabel(Form)
        self.showshipmenttype_2.setGeometry(QtCore.QRect(400, 480, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.showshipmenttype_2.setFont(font)
        self.showshipmenttype_2.setStyleSheet("QLabel{color:lightgrey;}\n"
"")
        self.showshipmenttype_2.setObjectName("showshipmenttype_2")
        self.confirm_2 = QtWidgets.QCommandLinkButton(Form)
        self.confirm_2.setGeometry(QtCore.QRect(30, 540, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.confirm_2.setFont(font)
        self.confirm_2.setIcon(icon)
        self.confirm_2.setObjectName("confirm_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.Tracking_Number.setText(QtWidgets.QApplication.translate("Form", "Tracking Number: ", None, -1))
        self.Info.setText(QtWidgets.QApplication.translate("Form", "Information", None, -1))
        self.confirm.setText(QtWidgets.QApplication.translate("Form", "CONFIRM", None, -1))
        self.rname.setText(QtWidgets.QApplication.translate("Form", "Receiver\'s name:", None, -1))
        self.sname.setText(QtWidgets.QApplication.translate("Form", "Sender\'s name: ", None, -1))
        self.senderAdd.setText(QtWidgets.QApplication.translate("Form", "Sender\'s address:", None, -1))
        self.raddr.setText(QtWidgets.QApplication.translate("Form", "Receiver\'s address:", None, -1))
        self.shipmenttype.setText(QtWidgets.QApplication.translate("Form", "Shipment type:", None, -1))
        self.showtrackingnumber.setText(QtWidgets.QApplication.translate("Form", "                showtrackingnumber", None, -1))
        self.showsname.setText(QtWidgets.QApplication.translate("Form", "Sender\'s name ", None, -1))
        self.showsAdd.setText(QtWidgets.QApplication.translate("Form", "Sender\'s address", None, -1))
        self.showrname.setText(QtWidgets.QApplication.translate("Form", "Receiver\'s name", None, -1))
        self.showradd.setText(QtWidgets.QApplication.translate("Form", "Receiver\'s address", None, -1))
        self.sendercon.setText(QtWidgets.QApplication.translate("Form", "Sender\'s contact number: ", None, -1))
        self.showsendercon.setText(QtWidgets.QApplication.translate("Form", "Sender\'s contact number", None, -1))
        self.showrcon.setText(QtWidgets.QApplication.translate("Form", "Sender\'s contact number", None, -1))
        self.rcon.setText(QtWidgets.QApplication.translate("Form", "Receiver\'s contact number: ", None, -1))
        self.showshipmenttype_2.setText(QtWidgets.QApplication.translate("Form", "Shipment type", None, -1))
        self.confirm_2.setText(QtWidgets.QApplication.translate("Form", "BACK", None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

